export const T = {
  en: {
    appName: "Me-Time",
    tagline: "A little something, just for you.",
    windowsLabel: "Free windows per week",
    durationLabel: "How long are they, usually?",
    interestsLabel: "What sounds good to you?",
    interestsHint: "Pick everything that feels right",
    cta: "Show me today's suggestion",
    todayLabel: "Today's suggestion",
    doneBtn: "I did this",
    anotherBtn: "Try another",
    weekLabel: "This week",
    backBtn: "Change preferences",
    nextFact: "Another fact",
    weekZero: "No me-time logged yet. Today's a good day to start.",
    weekOne: "You took 1 moment for yourself this week.",
    weekMany: (n) => `You took ${n} moments for yourself this week.`,
    donePhrases: [
      "That time was yours. Nobody else's.",
      "You showed up for yourself today.",
      "Small moments add up.",
      "You took time for yourself. That matters.",
      "That's one window of the week, just for you.",
    ],
    factLabel: "Did you know?",
    durationBadge: (d) => d < 60 ? `${d} min` : d === 60 ? "1 hour" : "1.5 hrs",
    durations: ["15 min", "30 min", "1 hour", "1.5 hrs+"],
  },
  mr: {
    appName: "माझा वेळ",
    tagline: "फक्त तुमच्यासाठी, थोडासा वेळ.",
    windowsLabel: "आठवड्यात मोकळे क्षण",
    durationLabel: "साधारणपणे किती वेळ असतात?",
    interestsLabel: "तुम्हाला काय आवडते?",
    interestsHint: "जे योग्य वाटेल ते सर्व निवडा",
    cta: "आजची सूचना दाखवा",
    todayLabel: "आजची सूचना",
    doneBtn: "मी हे केले",
    anotherBtn: "दुसरे सुचवा",
    weekLabel: "या आठवड्यात",
    backBtn: "आवडी बदला",
    nextFact: "आणखी एक तथ्य",
    weekZero: "अजून माझा वेळ नोंदवला नाही. आजपासून सुरुवात करा.",
    weekOne: "या आठवड्यात तुम्ही एकदा स्वतःसाठी वेळ काढला.",
    weekMany: (n) => `या आठवड्यात तुम्ही ${n} वेळा स्वतःसाठी वेळ काढला.`,
    donePhrases: [
      "हा वेळ फक्त तुमचा होता.",
      "आज तुम्ही स्वतःसाठी उभे राहिलात.",
      "लहान क्षण मोठे बदल घडवतात.",
      "तुम्ही स्वतःसाठी वेळ काढला. हे महत्त्वाचे आहे.",
      "हे तुमचे आहे. इतर कुणाचे नाही.",
    ],
    factLabel: "माहीत आहे का?",
    durationBadge: (d) => d < 60 ? `${d} मिनिटे` : d === 60 ? "१ तास" : "१.५ तास",
    durations: ["१५ मिनिटे", "३० मिनिटे", "१ तास", "१.५ तास+"],
  },
};

export const interests = {
  en: [
    { id: "movement", label: "Movement", icon: "🚶" },
    { id: "reading", label: "Reading", icon: "📖" },
    { id: "calm", label: "Quiet time", icon: "☁️" },
    { id: "creative", label: "Creative", icon: "🎨" },
    { id: "journaling", label: "Journaling", icon: "✏️" },
    { id: "cooking", label: "Cooking", icon: "🍳" },
    { id: "music", label: "Music", icon: "🎵" },
    { id: "selfcare", label: "Self-care", icon: "✨" },
    { id: "social", label: "Catch up", icon: "💬" },
    { id: "funfact", label: "Fun facts", icon: "💡" },
  ],
  mr: [
    { id: "movement", label: "व्यायाम", icon: "🚶" },
    { id: "reading", label: "वाचन", icon: "📖" },
    { id: "calm", label: "शांत वेळ", icon: "☁️" },
    { id: "creative", label: "सर्जनशील", icon: "🎨" },
    { id: "journaling", label: "लिखाण", icon: "✏️" },
    { id: "cooking", label: "स्वयंपाक", icon: "🍳" },
    { id: "music", label: "संगीत", icon: "🎵" },
    { id: "selfcare", label: "स्वतःची काळजी", icon: "✨" },
    { id: "social", label: "गप्पा मारा", icon: "💬" },
    { id: "funfact", label: "मजेदार तथ्ये", icon: "💡" },
  ],
};

export const activities = {
  en: [
    { title: "Read a few pages", desc: "No target, no pressure. Just pick up a book and read until you feel like stopping.", duration: 15, category: "reading" },
    { title: "Make your perfect cup", desc: "Tea, coffee, whatever you love. Make it slowly, exactly the way you like it.", duration: 15, category: "calm" },
    { title: "5-minute stretch", desc: "Neck, shoulders, lower back. Your body carries a lot. Give it a little attention.", duration: 15, category: "movement" },
    { title: "Write 3 things", desc: "Not a full journal — just 3 things on your mind, good or neutral. Gets the clutter out.", duration: 15, category: "journaling" },
    { title: "One favourite song, full volume", desc: "Close the door. Play the song you always skip past. Actually listen to it.", duration: 15, category: "music" },
    { title: "Quick skincare ritual", desc: "Even just moisturizer and sunscreen. Five minutes of taking care of your face.", duration: 15, category: "selfcare" },
    { title: "Short walk outside", desc: "No destination needed. Even 10 minutes of fresh air resets the nervous system.", duration: 30, category: "movement" },
    { title: "Call someone you like", desc: "Not to catch up on obligations — just to chat with someone who makes you feel good.", duration: 30, category: "social" },
    { title: "Watch a short video you've saved", desc: "That documentary clip, that recipe, that talk you bookmarked. Watch it without guilt.", duration: 30, category: "calm" },
    { title: "Try a new recipe", desc: "Something small — a sauce, a dessert, a snack. Just for you, just for fun.", duration: 60, category: "cooking" },
    { title: "Gentle yoga or stretching", desc: "A slow 20–30 minute flow. Nothing to achieve, just move the way that feels good.", duration: 60, category: "movement" },
    { title: "Draw or doodle", desc: "No skill required. Just put pen to paper and see what comes out.", duration: 30, category: "creative" },
    { title: "Start a show you've been putting off", desc: "Something you actually want to watch — not what everyone else is watching.", duration: 60, category: "calm" },
    { title: "Long bath with no rushing", desc: "Candle optional. Phone in the other room. Just water, warmth, and quiet.", duration: 60, category: "selfcare" },
    { title: "Plan something to look forward to", desc: "A trip, a dinner, a day out. Even just dreaming about it counts as self-care.", duration: 30, category: "journaling" },
    { title: "Get a fun fact", desc: "Sit back, relax, and learn one surprising thing about the world.", duration: 15, category: "funfact" },
  ],
  mr: [
    { title: "काही पाने वाचा", desc: "कोणतेही लक्ष्य नाही. एखादे पुस्तक उचला आणि मन भरेपर्यंत वाचा.", duration: 15, category: "reading" },
    { title: "तुमचा आवडता चहा बनवा", desc: "चहा, कॉफी, जे आवडते ते. हळूहळू, तुम्हाला आवडेल तसे बनवा.", duration: 15, category: "calm" },
    { title: "5 मिनिटे स्ट्रेचिंग", desc: "मान, खांदे, पाठ. तुमचे शरीर खूप काम करते. थोडी काळजी घ्या.", duration: 15, category: "movement" },
    { title: "3 गोष्टी लिहा", desc: "पूर्ण डायरी नाही — फक्त मनातल्या 3 गोष्टी लिहा. मन हलके होते.", duration: 15, category: "journaling" },
    { title: "एक आवडते गाणे, मोठ्याने", desc: "दार बंद करा. ते गाणे लावा जे तुम्ही नेहमी सोडून देता. खरोखर ऐका.", duration: 15, category: "music" },
    { title: "छोटी स्किनकेअर विधी", desc: "फक्त मॉइश्चरायझर आणि सनस्क्रीन. पाच मिनिटे स्वतःच्या चेहऱ्याची काळजी.", duration: 15, category: "selfcare" },
    { title: "बाहेर फेरफटका", desc: "कुठे जायचे नाही. फक्त 10 मिनिटे ताजी हवा मन रिफ्रेश करते.", duration: 30, category: "movement" },
    { title: "एखाद्याला फोन करा", desc: "कामासाठी नाही — फक्त ज्याच्याशी बोलणे आनंददायी वाटते त्याला फोन करा.", duration: 30, category: "social" },
    { title: "एखादा छोटा व्हिडिओ बघा", desc: "तो डॉक्युमेंटरी क्लिप, ती रेसिपी जी तुम्ही सेव्ह केली होती. आता बघा.", duration: 30, category: "calm" },
    { title: "नवी रेसिपी करून बघा", desc: "छोटेसे — एखादी चटणी, मिठाई, नाश्ता. फक्त आनंदासाठी.", duration: 60, category: "cooking" },
    { title: "हळुवार योगा किंवा स्ट्रेचिंग", desc: "20-30 मिनिटांचा धीमा योगा. साध्य करायचे काही नाही, फक्त हालचाल करा.", duration: 60, category: "movement" },
    { title: "चित्र काढा किंवा डूडल करा", desc: "कौशल्य लागत नाही. फक्त कागदावर पेन ठेवा आणि बघा काय होते.", duration: 30, category: "creative" },
    { title: "एखादी मालिका सुरू करा", desc: "जी तुम्हाला खरोखर बघायची आहे — सगळे बघतात म्हणून नाही.", duration: 60, category: "calm" },
    { title: "घाई न करता आंघोळ करा", desc: "मेणबत्ती ऐच्छिक. फोन दुसऱ्या खोलीत. फक्त पाणी, उबदारपणा, शांतता.", duration: 60, category: "selfcare" },
    { title: "काहीतरी नियोजन करा", desc: "सहल, जेवण, बाहेर जाणे. फक्त स्वप्न बघणेही स्वतःची काळजी आहे.", duration: 30, category: "journaling" },
    { title: "एक मजेदार तथ्य जाणून घ्या", desc: "आराम करा आणि जगाबद्दल एक आश्चर्यकारक गोष्ट शिका.", duration: 15, category: "funfact" },
  ],
};

export const funfacts = {
  en: [
    { topic: "Nature", fact: "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that was still perfectly edible." },
    { topic: "Human body", fact: "Your nose can detect over 1 trillion different smells — far more than scientists previously thought." },
    { topic: "Space", fact: "A day on Venus is longer than a year on Venus. It rotates so slowly it takes longer to spin once than to orbit the Sun." },
    { topic: "Animals", fact: "Crows can recognize human faces and will hold grudges against people who have been unkind to them." },
    { topic: "Food", fact: "Apples, pears, and roses all belong to the same plant family — Rosaceae." },
    { topic: "Ocean", fact: "We have mapped only about 20% of the ocean floor. More of the moon's surface has been mapped than our own sea bed." },
    { topic: "History", fact: "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza." },
    { topic: "Plants", fact: "Trees in a forest communicate and share nutrients through underground fungal networks — sometimes called the 'wood wide web'." },
    { topic: "Science", fact: "Hot water can freeze faster than cold water under certain conditions. This is called the Mpemba effect." },
    { topic: "Music", fact: "Listening to music you love triggers the same brain reward system as eating food or falling in love." },
    { topic: "Sleep", fact: "Humans are the only mammals that willingly delay sleep. Every other animal sleeps when it needs to." },
    { topic: "Language", fact: "The word 'set' has the most definitions in the English language — over 430 different meanings." },
  ],
  mr: [
    { topic: "निसर्ग", fact: "मध कधीही खराब होत नाही. इजिप्शियन समाधींमध्ये 3,000 वर्षे जुने मध सापडले जे अजूनही खाण्यायोग्य होते." },
    { topic: "मानवी शरीर", fact: "आपले नाक 1 ट्रिलियनपेक्षा जास्त वेगवेगळ्या वासांची ओळख करू शकते." },
    { topic: "अंतराळ", fact: "शुक्र ग्रहावर एक दिवस, एका वर्षापेक्षा जास्त असतो — त्याला स्वतःभोवती एक फेरी पूर्ण करायला सूर्याभोवती एक फेरीपेक्षा जास्त वेळ लागतो." },
    { topic: "प्राणी", fact: "कावळे माणसांचे चेहरे ओळखू शकतात आणि ज्यांनी त्यांच्याशी वाईट वागणूक केली त्यांच्यावर ते राग धरतात." },
    { topic: "अन्न", fact: "सफरचंद, नाशपाती आणि गुलाब सर्व एकाच वनस्पती कुटुंबातील आहेत — Rosaceae." },
    { topic: "महासागर", fact: "आपण अजूनही फक्त 20% समुद्राचा तळ नकाशावर आणला आहे. चंद्राच्या पृष्ठभागाचा नकाशा आपल्या समुद्राच्या तळापेक्षा जास्त तयार झाला आहे." },
    { topic: "इतिहास", fact: "क्लियोपात्रा कालाने चंद्रावरील उतरणीच्या जवळ होती, ग्रेट पिरॅमिडच्या बांधकामापेक्षा." },
    { topic: "वनस्पती", fact: "जंगलातील झाडे भूमिगत बुरशीच्या जाळ्याद्वारे एकमेकांशी संवाद साधतात — याला 'वुड वाइड वेब' म्हणतात." },
    { topic: "विज्ञान", fact: "काही परिस्थितींमध्ये गरम पाणी थंड पाण्यापेक्षा जलद गोठू शकते — याला म्पेम्बा इफेक्ट म्हणतात." },
    { topic: "संगीत", fact: "आवडते संगीत ऐकताना मेंदूमध्ये तेच बक्षीस केंद्र सक्रिय होते जे अन्न खाताना किंवा प्रेमात पडताना होते." },
    { topic: "झोप", fact: "माणूस हा एकमेव सस्तन प्राणी आहे जो स्वेच्छेने झोप पुढे ढकलतो. इतर सर्व प्राणी गरज भासताच झोपतात." },
    { topic: "भाषा", fact: "मराठी भाषा ही जगातील सर्वाधिक बोलल्या जाणाऱ्या भाषांपैकी एक असून ती सुमारे 8 कोटी लोक बोलतात." },
  ],
};
